import { FeContract } from "@/types/weclapp/contract";
import { PaginatedResponse } from "@scaleits-solutions-gmbh/services";

const mockContracts: FeContract[] = [
    {
        id: "1",
        number: "C-2024-001",
        customer: "Edler & Stiegler Consulting GmbH",
        status: "active",
        startDate: "2024-01-15",
        endDate: "2024-12-31",
        latestCancellationWarningQuantity: 30,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "Consulting Services", quantity: 120, unitPrice: "150" },
            { name: "Project Management", quantity: 40, unitPrice: "200" },
        ],
    },
    {
        id: "2",
        number: "C-2024-002",
        customer: "Tech Solutions AG",
        status: "active",
        startDate: "2024-02-01",
        endDate: "2024-11-30",
        latestCancellationWarningQuantity: 60,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "Software Development", quantity: 200, unitPrice: "120" },
            { name: "Quality Assurance", quantity: 80, unitPrice: "100" },
        ],
    },
    {
        id: "3",
        number: "C-2024-003",
        customer: "Digital Innovations GmbH",
        status: "active",
        startDate: "2024-01-20",
        endDate: "2024-10-31",
        latestCancellationWarningQuantity: 45,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "UI/UX Design", quantity: 160, unitPrice: "130" },
            { name: "Frontend Development", quantity: 120, unitPrice: "110" },
        ],
    },
    {
        id: "4",
        number: "C-2024-004",
        customer: "Cloud Systems Ltd",
        status: "active",
        startDate: "2024-03-01",
        endDate: "2024-12-31",
        latestCancellationWarningQuantity: 90,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "Cloud Migration", quantity: 250, unitPrice: "140" },
            { name: "DevOps Implementation", quantity: 100, unitPrice: "160" },
        ],
    },
    {
        id: "5",
        number: "C-2024-005",
        customer: "Data Analytics Corp",
        status: "active",
        startDate: "2024-02-15",
        endDate: "2024-11-30",
        latestCancellationWarningQuantity: 30,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "Data Analysis", quantity: 180, unitPrice: "125" },
            { name: "Machine Learning Models", quantity: 60, unitPrice: "180" },
        ],
    },
    {
        id: "6",
        number: "C-2024-006",
        customer: "Mobile Apps GmbH",
        status: "active",
        startDate: "2024-01-10",
        endDate: "2024-09-30",
        latestCancellationWarningQuantity: 60,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "Mobile Development", quantity: 220, unitPrice: "135" },
            { name: "App Store Optimization", quantity: 40, unitPrice: "90" },
        ],
    },
    {
        id: "7",
        number: "C-2024-007",
        customer: "Web Solutions AG",
        status: "active",
        startDate: "2024-02-20",
        endDate: "2024-08-31",
        latestCancellationWarningQuantity: 45,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "Web Development", quantity: 140, unitPrice: "115" },
            { name: "SEO Optimization", quantity: 60, unitPrice: "85" },
        ],
    },
    {
        id: "8",
        number: "C-2024-008",
        customer: "AI Technologies Ltd",
        status: "active",
        startDate: "2024-03-15",
        endDate: "2024-12-31",
        latestCancellationWarningQuantity: 90,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "AI Implementation", quantity: 400, unitPrice: "200" },
            { name: "Model Training", quantity: 120, unitPrice: "250" },
        ],
    },
    {
        id: "9",
        number: "C-2024-009",
        customer: "Security Systems GmbH",
        status: "active",
        startDate: "2024-01-25",
        endDate: "2024-10-31",
        latestCancellationWarningQuantity: 60,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "Security Audit", quantity: 260, unitPrice: "160" },
            { name: "Penetration Testing", quantity: 80, unitPrice: "175" },
        ],
    },
    {
        id: "10",
        number: "C-2024-010",
        customer: "Network Solutions AG",
        status: "active",
        startDate: "2024-02-10",
        endDate: "2024-11-30",
        latestCancellationWarningQuantity: 45,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "Network Setup", quantity: 190, unitPrice: "145" },
            { name: "Network Monitoring", quantity: 120, unitPrice: "95" },
        ],
    },
    {
        id: "11",
        number: "C-2024-011",
        customer: "Database Experts GmbH",
        status: "active",
        startDate: "2024-01-30",
        endDate: "2024-09-30",
        latestCancellationWarningQuantity: 30,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "Database Optimization", quantity: 170, unitPrice: "155" },
            { name: "Data Migration", quantity: 100, unitPrice: "165" },
        ],
    },
    {
        id: "12",
        number: "C-2024-012",
        customer: "DevOps Solutions Ltd",
        status: "active",
        startDate: "2024-03-01",
        endDate: "2024-12-31",
        latestCancellationWarningQuantity: 90,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "DevOps Implementation", quantity: 280, unitPrice: "170" },
            { name: "CI/CD Pipeline Setup", quantity: 80, unitPrice: "140" },
        ],
    },
    {
        id: "13",
        number: "C-2024-013",
        customer: "Testing Services AG",
        status: "active",
        startDate: "2024-02-05",
        endDate: "2024-08-31",
        latestCancellationWarningQuantity: 45,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "Quality Assurance", quantity: 120, unitPrice: "110" },
            { name: "Automated Testing", quantity: 160, unitPrice: "125" },
        ],
    },
    {
        id: "14",
        number: "C-2024-014",
        customer: "API Development GmbH",
        status: "active",
        startDate: "2024-01-20",
        endDate: "2024-10-31",
        latestCancellationWarningQuantity: 60,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "API Development", quantity: 200, unitPrice: "130" },
            { name: "API Documentation", quantity: 60, unitPrice: "100" },
        ],
    },
    {
        id: "15",
        number: "C-2024-015",
        customer: "Microservices Corp",
        status: "active",
        startDate: "2024-03-10",
        endDate: "2024-12-31",
        latestCancellationWarningQuantity: 90,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "Microservices Architecture", quantity: 320, unitPrice: "180" },
            { name: "Service Mesh Implementation", quantity: 120, unitPrice: "200" },
        ],
    },
    {
        id: "16",
        number: "C-2024-016",
        customer: "Blockchain Solutions AG",
        status: "active",
        startDate: "2024-02-15",
        endDate: "2024-11-30",
        latestCancellationWarningQuantity: 60,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "Blockchain Implementation", quantity: 360, unitPrice: "220" },
            { name: "Smart Contract Development", quantity: 80, unitPrice: "240" },
        ],
    },
    {
        id: "17",
        number: "C-2024-017",
        customer: "IoT Services GmbH",
        status: "active",
        startDate: "2024-01-25",
        endDate: "2024-10-31",
        latestCancellationWarningQuantity: 45,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "IoT Integration", quantity: 240, unitPrice: "160" },
            { name: "Sensor Network Setup", quantity: 120, unitPrice: "140" },
        ],
    },
    {
        id: "18",
        number: "C-2024-018",
        customer: "Machine Learning Corp",
        status: "active",
        startDate: "2024-03-05",
        endDate: "2024-12-31",
        latestCancellationWarningQuantity: 90,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "ML Model Development", quantity: 440, unitPrice: "250" },
            { name: "Data Pipeline Setup", quantity: 160, unitPrice: "180" },
        ],
    },
    {
        id: "19",
        number: "C-2024-019",
        customer: "Big Data Solutions AG",
        status: "active",
        startDate: "2024-02-20",
        endDate: "2024-11-30",
        latestCancellationWarningQuantity: 60,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "Big Data Processing", quantity: 340, unitPrice: "190" },
            { name: "Data Warehouse Setup", quantity: 200, unitPrice: "170" },
        ],
    },
    {
        id: "20",
        number: "C-2024-020",
        customer: "Cloud Native GmbH",
        status: "active",
        startDate: "2024-01-15",
        endDate: "2024-10-31",
        latestCancellationWarningQuantity: 45,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "Cloud Native Development", quantity: 260, unitPrice: "175" },
            { name: "Kubernetes Setup", quantity: 120, unitPrice: "185" },
        ],
    },
    {
        id: "21",
        number: "C-2024-021",
        customer: "Serverless Solutions Ltd",
        status: "active",
        startDate: "2024-02-10",
        endDate: "2024-09-30",
        latestCancellationWarningQuantity: 60,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "Serverless Architecture", quantity: 220, unitPrice: "155" },
            { name: "Function Development", quantity: 180, unitPrice: "135" },
        ],
    },
    {
        id: "22",
        number: "C-2024-022",
        customer: "Container Services AG",
        status: "active",
        startDate: "2024-01-30",
        endDate: "2024-08-31",
        latestCancellationWarningQuantity: 45,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "Container Orchestration", quantity: 180, unitPrice: "165" },
            { name: "Docker Implementation", quantity: 100, unitPrice: "145" },
        ],
    },
    {
        id: "23",
        number: "C-2024-023",
        customer: "Monitoring Systems GmbH",
        status: "active",
        startDate: "2024-02-25",
        endDate: "2024-09-30",
        latestCancellationWarningQuantity: 45,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "System Monitoring", quantity: 160, unitPrice: "125" },
            { name: "Alert System Setup", quantity: 80, unitPrice: "115" },
        ],
    },
    {
        id: "24",
        number: "C-2024-024",
        customer: "Backup Solutions Corp",
        status: "active",
        startDate: "2024-01-20",
        endDate: "2024-08-31",
        latestCancellationWarningQuantity: 30,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "Backup Implementation", quantity: 140, unitPrice: "135" },
            { name: "Disaster Recovery Setup", quantity: 100, unitPrice: "155" },
        ],
    },
    {
        id: "25",
        number: "C-2024-025",
        customer: "Disaster Recovery AG",
        status: "active",
        startDate: "2024-03-01",
        endDate: "2024-11-30",
        latestCancellationWarningQuantity: 90,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "DR Strategy", quantity: 300, unitPrice: "180" },
            { name: "Business Continuity Planning", quantity: 120, unitPrice: "200" },
        ],
    },
    {
        id: "26",
        number: "C-2024-026",
        customer: "Compliance Services GmbH",
        status: "active",
        startDate: "2024-02-15",
        endDate: "2024-09-30",
        latestCancellationWarningQuantity: 60,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "Compliance Audit", quantity: 200, unitPrice: "150" },
            { name: "Policy Development", quantity: 80, unitPrice: "130" },
        ],
    },
    {
        id: "27",
        number: "C-2024-027",
        customer: "Performance Optimization Ltd",
        status: "active",
        startDate: "2024-01-25",
        endDate: "2024-09-30",
        latestCancellationWarningQuantity: 45,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "Performance Tuning", quantity: 240, unitPrice: "160" },
            { name: "Load Testing", quantity: 120, unitPrice: "140" },
        ],
    },
    {
        id: "28",
        number: "C-2024-028",
        customer: "Scalability Solutions AG",
        status: "active",
        startDate: "2024-02-20",
        endDate: "2024-10-31",
        latestCancellationWarningQuantity: 60,
        latestCancellationWarningUnit: "days",
        items: [
            { name: "Scalability Planning", quantity: 280, unitPrice: "170" },
            { name: "Infrastructure Scaling", quantity: 160, unitPrice: "190" },
        ],
    },
];


export const mockGetContracts = async (page: number, pageSize: number): Promise<PaginatedResponse<FeContract>> => {
    const startIndex = (page - 1) * pageSize;
    const endIndex = startIndex + pageSize;
    const paginatedItems = mockContracts.slice(startIndex, endIndex);
    
    return {
        items: paginatedItems,
        total: mockContracts.length,
        page: page,
        pageSize: pageSize,
        totalPages: Math.ceil(mockContracts.length / pageSize),
    };
}