import { FeSalesInvoice } from "@/types/weclapp/sales-invoice";
import { PaginatedResponse } from "@scaleits-solutions-gmbh/services";

export const mockSalesInvoices: FeSalesInvoice[] = [
    {
      id: "1",
      number: "SI-2025-001",
      customer: "Kappa Consulting GmbH",
      grossAmount: "20425",
      netAmount: "18791",
      status: "active",
      items: [
        { name: "CI/CD Pipeline Setup", quantity: 19, unitPrice: "55" },
        { name: "Incident Response", quantity: 13, unitPrice: "60" },
        { name: "Machine Learning Prototyping", quantity: 11, unitPrice: "65" },
        { name: "Accessibility Audit", quantity: 6, unitPrice: "45" },
        { name: "Data Lake Design", quantity: 12, unitPrice: "55" },
        { name: "KPI Dashboard", quantity: 17, unitPrice: "50" },
        { name: "Localization", quantity: 14, unitPrice: "45" },
        { name: "Metadata Catalog", quantity: 20, unitPrice: "50" },
        { name: "Serverless Function Development", quantity: 8, unitPrice: "60" },
        { name: "Voice Interface Design", quantity: 10, unitPrice: "55" },
        { name: "Risk Management", quantity: 16, unitPrice: "50" },
        { name: "Blue/Green Deployment", quantity: 9, unitPrice: "65" },
      ],
    },
    {
      id: "2",
      number: "SI-2025-002",
      customer: "Gamma Innovations GmbH",
      grossAmount: "17075",
      netAmount: "15709",
      status: "active",
      items: [
        { name: "Containerization", quantity: 10, unitPrice: "60" },
        { name: "Streaming Data Processing", quantity: 12, unitPrice: "55" },
        { name: "Digital Twin Implementation", quantity: 7, unitPrice: "65" },
        { name: "ETL Development", quantity: 18, unitPrice: "45" },
        { name: "Product Roadmap Creation", quantity: 11, unitPrice: "55" },
        { name: "Data Privacy Impact Assessment", quantity: 5, unitPrice: "70" },
        { name: "Voice Interface Design", quantity: 13, unitPrice: "50" },
        { name: "Competitive Benchmarking", quantity: 14, unitPrice: "45" },
        { name: "Usability Testing", quantity: 9, unitPrice: "60" },
        { name: "Observability Implementation", quantity: 15, unitPrice: "50" },
        { name: "A/B Testing", quantity: 8, unitPrice: "65" },
        { name: "Governance Setup", quantity: 16, unitPrice: "45" },
      ],
    },
    {
      id: "3",
      number: "SI-2025-003",
      customer: "Lambda Systems GmbH",
      grossAmount: "18495",
      netAmount: "17015",
      status: "active",
      items: [
        { name: "Discovery Workshop", quantity: 14, unitPrice: "55" },
        { name: "Backend Development", quantity: 11, unitPrice: "60" },
        { name: "API Design", quantity: 7, unitPrice: "65" },
        { name: "Monitoring & Alerting", quantity: 18, unitPrice: "45" },
        { name: "Zero Trust Architecture", quantity: 12, unitPrice: "60" },
        { name: "Metadata Catalog", quantity: 10, unitPrice: "50" },
        { name: "Financial Modeling", quantity: 8, unitPrice: "65" },
        { name: "Sprint Planning Facilitation", quantity: 6, unitPrice: "50" },
        { name: "Chaos Engineering Workshop", quantity: 13, unitPrice: "55" },
        { name: "Data Governance Framework", quantity: 9, unitPrice: "60" },
        { name: "ISO 27001 Preparation", quantity: 16, unitPrice: "45" },
        { name: "Metadata Catalog", quantity: 5, unitPrice: "70" },
      ],
    },
    {
      id: "4",
      number: "SI-2025-004",
      customer: "Sigma Technologies GmbH",
      grossAmount: "20120",
      netAmount: "18510",
      status: "active",
      items: [
        { name: "Requirements Gathering", quantity: 15, unitPrice: "55" },
        { name: "Frontend Development", quantity: 14, unitPrice: "55" },
        { name: "Integration Testing", quantity: 10, unitPrice: "60" },
        { name: "Post-Deployment Support", quantity: 6, unitPrice: "65" },
        { name: "Data Modeling", quantity: 12, unitPrice: "55" },
        { name: "Predictive Analytics", quantity: 8, unitPrice: "65" },
        { name: "Edge Computing", quantity: 11, unitPrice: "60" },
        { name: "Chatbot Development", quantity: 9, unitPrice: "60" },
        { name: "RPA Workflow Design", quantity: 7, unitPrice: "65" },
        { name: "Log Aggregation", quantity: 13, unitPrice: "50" },
        { name: "Market Analysis", quantity: 17, unitPrice: "45" },
        { name: "OKR Tracking", quantity: 5, unitPrice: "70" },
      ],
    },
    {
      id: "5",
      number: "SI-2025-005",
      customer: "Zeta Dynamics GmbH",
      grossAmount: "20635",
      netAmount: "18984",
      status: "active",
      items: [
        { name: "Design System Creation", quantity: 11, unitPrice: "60" },
        { name: "Accessibility Audit", quantity: 14, unitPrice: "55" },
        { name: "Localization", quantity: 9, unitPrice: "65" },
        { name: "SEO Optimization", quantity: 12, unitPrice: "55" },
        { name: "Content Migration", quantity: 15, unitPrice: "50" },
        { name: "Multivariate Testing", quantity: 8, unitPrice: "65" },
        { name: "CRM Integration", quantity: 10, unitPrice: "60" },
        { name: "ERP Customization", quantity: 7, unitPrice: "65" },
        { name: "Legacy System Decommission", quantity: 13, unitPrice: "50" },
        { name: "Knowledge Transfer", quantity: 16, unitPrice: "45" },
        { name: "GDPR Assessment", quantity: 6, unitPrice: "70" },
        { name: "High Availability Setup", quantity: 17, unitPrice: "45" },
      ],
    },
    {
      id: "6",
      number: "SI-2025-006",
      customer: "Alpha Solutions GmbH",
      grossAmount: "19550",
      netAmount: "17986",
      status: "active",
      items: [
        { name: "Load Balancing", quantity: 18, unitPrice: "45" },
        { name: "Log Aggregation", quantity: 14, unitPrice: "55" },
        { name: "Single Sign-On", quantity: 8, unitPrice: "65" },
        { name: "Multi-factor Authentication", quantity: 10, unitPrice: "60" },
        { name: "Data Encryption", quantity: 12, unitPrice: "55" },
        { name: "Key Management", quantity: 9, unitPrice: "65" },
        { name: "Secrets Rotation", quantity: 13, unitPrice: "50" },
        { name: "Dynamic Scaling", quantity: 11, unitPrice: "60" },
        { name: "Canary Release", quantity: 7, unitPrice: "65" },
        { name: "Data Quality Checks", quantity: 15, unitPrice: "50" },
        { name: "Heatmap Analysis", quantity: 16, unitPrice: "45" },
        { name: "Customer Journey Mapping", quantity: 6, unitPrice: "70" },
      ],
    },
    {
      id: "7",
      number: "SI-2025-007",
      customer: "Omega Consulting GmbH",
      grossAmount: "17880",
      netAmount: "16450",
      status: "active",
      items: [
        { name: "Usability Testing", quantity: 12, unitPrice: "55" },
        { name: "Heatmap Analysis", quantity: 14, unitPrice: "55" },
        { name: "Eye Tracking Study", quantity: 9, unitPrice: "65" },
        { name: "Gamification Strategy", quantity: 7, unitPrice: "65" },
        { name: "OKR Tracking", quantity: 11, unitPrice: "60" },
        { name: "Retrospective Facilitation", quantity: 8, unitPrice: "65" },
        { name: "Sprint Planning Facilitation", quantity: 10, unitPrice: "60" },
        { name: "Product Roadmap Creation", quantity: 16, unitPrice: "45" },
        { name: "Go-to-Market Strategy", quantity: 5, unitPrice: "70" },
        { name: "Partner Integration", quantity: 13, unitPrice: "50" },
        { name: "Third-party API Assessment", quantity: 15, unitPrice: "45" },
        { name: "Logging Aggregation", quantity: 6, unitPrice: "70" },
      ],
    },
    {
      id: "8",
      number: "SI-2025-008",
      customer: "Theta Solutions GmbH",
      grossAmount: "19925",
      netAmount: "18331",
      status: "active",
      items: [
        { name: "High Availability Setup", quantity: 12, unitPrice: "55" },
        { name: "Load Balancing", quantity: 14, unitPrice: "55" },
        { name: "Network Segmentation", quantity: 8, unitPrice: "65" },
        { name: "Zero Trust Architecture", quantity: 9, unitPrice: "65" },
        { name: "LDAP Integration", quantity: 11, unitPrice: "60" },
        { name: "Single Sign-On", quantity: 13, unitPrice: "50" },
        { name: "Monitoring & Alerting", quantity: 15, unitPrice: "50" },
        { name: "Key Management", quantity: 10, unitPrice: "60" },
        { name: "Disaster Recovery Drill", quantity: 6, unitPrice: "70" },
        { name: "Data Lineage Mapping", quantity: 7, unitPrice: "65" },
        { name: "Metadata Catalog", quantity: 16, unitPrice: "45" },
        { name: "Dynamic Scaling", quantity: 5, unitPrice: "70" },
      ],
    },
    {
      id: "9",
      number: "SI-2025-009",
      customer: "Delta Systems GmbH",
      grossAmount: "18615",
      netAmount: "17125",
      status: "active",
      items: [
        { name: "Metadata Catalog", quantity: 10, unitPrice: "60" },
        { name: "Data Lineage Mapping", quantity: 8, unitPrice: "65" },
        { name: "Data Privacy Impact Assessment", quantity: 5, unitPrice: "70" },
        { name: "Data Quality Checks", quantity: 14, unitPrice: "55" },
        { name: "Data Governance Framework", quantity: 12, unitPrice: "55" },
        { name: "Custom Reporting", quantity: 15, unitPrice: "50" },
        { name: "Financial Modeling", quantity: 7, unitPrice: "65" },
        { name: "Market Analysis", quantity: 13, unitPrice: "50" },
        { name: "Competitive Benchmarking", quantity: 9, unitPrice: "60" },
        { name: "KPI Dashboard", quantity: 16, unitPrice: "45" },
        { name: "OKR Tracking", quantity: 11, unitPrice: "60" },
        { name: "Data Lake Design", quantity: 6, unitPrice: "70" },
      ],
    },
    {
      id: "10",
      number: "SI-2025-010",
      customer: "Eta Dynamics GmbH",
      grossAmount: "19190",
      netAmount: "17655",
      status: "active",
      items: [
        { name: "Discovery Workshop", quantity: 11, unitPrice: "60" },
        {
          name: "Technical Specification Development",
          quantity: 13,
          unitPrice: "55",
        },
        { name: "Backend Development", quantity: 15, unitPrice: "50" },
        { name: "API Design", quantity: 8, unitPrice: "65" },
        { name: "Integration Testing", quantity: 9, unitPrice: "65" },
        { name: "End-to-End Testing", quantity: 12, unitPrice: "55" },
        { name: "Performance Profiling", quantity: 10, unitPrice: "60" },
        { name: "Security Hardening", quantity: 14, unitPrice: "55" },
        { name: "User Training", quantity: 6, unitPrice: "70" },
        { name: "Deployment Automation", quantity: 7, unitPrice: "65" },
        { name: "Post-Deployment Support", quantity: 16, unitPrice: "45" },
        { name: "Maintenance", quantity: 5, unitPrice: "70" },
      ],
    },
    {
      id: "11",
      number: "SI-2025-011",
      customer: "Beta Solutions GmbH",
      grossAmount: "17560",
      netAmount: "16155",
      status: "active",
      items: [
        { name: "Data Modeling", quantity: 7, unitPrice: "65" },
        { name: "ETL Development", quantity: 14, unitPrice: "55" },
        { name: "Dashboard Creation", quantity: 12, unitPrice: "55" },
        { name: "Predictive Analytics", quantity: 8, unitPrice: "65" },
        { name: "Machine Learning Prototyping", quantity: 10, unitPrice: "60" },
        { name: "Model Training", quantity: 9, unitPrice: "65" },
        { name: "Model Evaluation", quantity: 16, unitPrice: "45" },
        { name: "A/B Testing", quantity: 11, unitPrice: "60" },
        { name: "Feature Flag Implementation", quantity: 13, unitPrice: "50" },
        { name: "Infrastructure as Code", quantity: 5, unitPrice: "70" },
        {
          name: "Serverless Function Development",
          quantity: 15,
          unitPrice: "50",
        },
        { name: "Edge Computing", quantity: 6, unitPrice: "70" },
      ],
    },
    {
      id: "12",
      number: "SI-2025-012",
      customer: "Epsilon Technologies GmbH",
      grossAmount: "20045",
      netAmount: "18441",
      status: "active",
      items: [
        { name: "Digital Twin Implementation", quantity: 8, unitPrice: "65" },
        { name: "Voice Interface Design", quantity: 9, unitPrice: "65" },
        { name: "Chatbot Development", quantity: 14, unitPrice: "55" },
        { name: "RPA Workflow Design", quantity: 12, unitPrice: "55" },
        { name: "Blockchain Smart Contract", quantity: 10, unitPrice: "60" },
        { name: "NFT Marketplace Integration", quantity: 16, unitPrice: "45" },
        { name: "AR/VR Prototype", quantity: 7, unitPrice: "65" },
        { name: "Spatial Mapping", quantity: 11, unitPrice: "60" },
        { name: "Design System Creation", quantity: 13, unitPrice: "50" },
        { name: "Accessibility Audit", quantity: 15, unitPrice: "45" },
        { name: "Localization", quantity: 6, unitPrice: "70" },
        { name: "SEO Optimization", quantity: 5, unitPrice: "70" },
      ],
    },
  ] as const;


  export const mockGetSalesInvoices = async (
    searchText: string,
    page: number,
    pageSize: number
  ): Promise<PaginatedResponse<FeSalesInvoice>> => {
    // Filter salesInvoices based on search text
    let filteredSalesInvoices = mockSalesInvoices;
  
    if (searchText && searchText.trim() !== "") {
      const searchLower = searchText.toLowerCase().trim();
      filteredSalesInvoices = mockSalesInvoices.filter((salesInvoice) => {
        return (
          salesInvoice.number.toLowerCase().includes(searchLower) ||
          salesInvoice.customer.toLowerCase().includes(searchLower) ||
          salesInvoice.status.toLowerCase().includes(searchLower) ||
          salesInvoice.grossAmount.includes(searchLower) ||
          salesInvoice.netAmount.includes(searchLower) ||
          salesInvoice.items.some((item) =>
            item.name.toLowerCase().includes(searchLower)
          )
        );
      });
    }
  
    const startIndex = (page - 1) * pageSize;
    const endIndex = startIndex + pageSize;
    const paginatedItems = filteredSalesInvoices.slice(startIndex, endIndex);
  
    return {
      items: paginatedItems,
      total: filteredSalesInvoices.length,
      page: page,
      pageSize: pageSize,
      totalPages: Math.ceil(filteredSalesInvoices.length / pageSize),
    };
  };