import { FeProject } from "@/types/weclapp/project";
import { PaginatedResponse } from "@scaleits-solutions-gmbh/services";

export const mockProjects: FeProject[] = [
    {
        id: "1",
        number: "P-2024-001",
        customer: "Edler & Stiegler Consulting GmbH",
        status: "active",
        startDate: "2024-01-15",
        endDate: "2024-06-15",
        members: [
            { id: "1", role: "PL", userId: "user1", firstName: "John", lastName: "Doe", email: "john.doe@company.com" },
            { id: "2", role: "developer", userId: "user2", firstName: "Jane", lastName: "Smith", email: "jane.smith@company.com" },
        ],
    },
    {
        id: "2",
        number: "P-2024-002",
        customer: "Tech Solutions AG",
        status: "active",
        startDate: "2024-02-01",
        endDate: "2024-08-01",
        members: [
            { id: "3", role: "PL", userId: "user3", firstName: "Mike", lastName: "Johnson", email: "mike.johnson@company.com" },
            { id: "4", role: "developer", userId: "user4", firstName: "Sarah", lastName: "Wilson", email: "sarah.wilson@company.com" },
            { id: "5", role: "designer", userId: "user5", firstName: "Alex", lastName: "Brown", email: "alex.brown@company.com" },
        ],
    },
    {
        id: "3",
        number: "P-2024-003",
        customer: "Digital Innovations GmbH",
        status: "active",
        startDate: "2024-01-20",
        endDate: "2024-05-20",
        members: [
            { id: "6", role: "PL", userId: "user6", firstName: "Lisa", lastName: "Davis", email: "lisa.davis@company.com" },
            { id: "7", role: "developer", userId: "user7", firstName: "Tom", lastName: "Miller", email: "tom.miller@company.com" },
        ],
    },
    {
        id: "4",
        number: "P-2024-004",
        customer: "Cloud Systems Ltd",
        status: "active",
        startDate: "2024-03-01",
        endDate: "2024-09-01",
        members: [
            { id: "8", role: "PL", userId: "user8", firstName: "David", lastName: "Garcia", email: "david.garcia@company.com" },
            { id: "9", role: "developer", userId: "user9", firstName: "Emma", lastName: "Taylor", email: "emma.taylor@company.com" },
            { id: "10", role: "devops", userId: "user10", firstName: "Chris", lastName: "Anderson", email: "chris.anderson@company.com" },
        ],
    },
    {
        id: "5",
        number: "P-2024-005",
        customer: "Data Analytics Corp",
        status: "active",
        startDate: "2024-02-15",
        endDate: "2024-07-15",
        members: [
            { id: "11", role: "PL", userId: "user11", firstName: "Rachel", lastName: "Martinez", email: "rachel.martinez@company.com" },
            { id: "12", role: "data_scientist", userId: "user12", firstName: "Kevin", lastName: "Lee", email: "kevin.lee@company.com" },
        ],
    },
    {
        id: "6",
        number: "P-2024-006",
        customer: "Mobile Apps GmbH",
        status: "active",
        startDate: "2024-01-10",
        endDate: "2024-06-10",
        members: [
            { id: "13", role: "PL", userId: "user13", firstName: "Amanda", lastName: "White", email: "amanda.white@company.com" },
            { id: "14", role: "mobile_developer", userId: "user14", firstName: "Ryan", lastName: "Clark", email: "ryan.clark@company.com" },
            { id: "15", role: "ui_ux_designer", userId: "user15", firstName: "Sophie", lastName: "Lewis", email: "sophie.lewis@company.com" },
        ],
    },
    {
        id: "7",
        number: "P-2024-007",
        customer: "Web Solutions AG",
        status: "active",
        startDate: "2024-02-20",
        endDate: "2024-05-20",
        members: [
            { id: "16", role: "PL", userId: "user16", firstName: "Daniel", lastName: "Hall", email: "daniel.hall@company.com" },
            { id: "17", role: "frontend_developer", userId: "user17", firstName: "Jessica", lastName: "Allen", email: "jessica.allen@company.com" },
            { id: "18", role: "backend_developer", userId: "user18", firstName: "Mark", lastName: "Young", email: "mark.young@company.com" },
        ],
    },
    {
        id: "8",
        number: "P-2024-008",
        customer: "AI Technologies Ltd",
        status: "active",
        startDate: "2024-03-15",
        endDate: "2024-10-15",
        members: [
            { id: "19", role: "PL", userId: "user19", firstName: "Nicole", lastName: "King", email: "nicole.king@company.com" },
            { id: "20", role: "ai_engineer", userId: "user20", firstName: "Jason", lastName: "Wright", email: "jason.wright@company.com" },
            { id: "21", role: "ml_specialist", userId: "user21", firstName: "Michelle", lastName: "Green", email: "michelle.green@company.com" },
        ],
    },
    {
        id: "9",
        number: "P-2024-009",
        customer: "Security Systems GmbH",
        status: "active",
        startDate: "2024-01-25",
        endDate: "2024-06-25",
        members: [
            { id: "22", role: "PL", userId: "user22", firstName: "Robert", lastName: "Scott", email: "robert.scott@company.com" },
            { id: "23", role: "security_analyst", userId: "user23", firstName: "Laura", lastName: "Adams", email: "laura.adams@company.com" },
            { id: "24", role: "penetration_tester", userId: "user24", firstName: "James", lastName: "Baker", email: "james.baker@company.com" },
        ],
    },
    {
        id: "10",
        number: "P-2024-010",
        customer: "Network Solutions AG",
        status: "active",
        startDate: "2024-02-10",
        endDate: "2024-07-10",
        members: [
            { id: "25", role: "PL", userId: "user25", firstName: "Patricia", lastName: "Gonzalez", email: "patricia.gonzalez@company.com" },
            { id: "26", role: "network_engineer", userId: "user26", firstName: "Thomas", lastName: "Nelson", email: "thomas.nelson@company.com" },
        ],
    },
    {
        id: "11",
        number: "P-2024-011",
        customer: "Database Experts GmbH",
        status: "active",
        startDate: "2024-01-30",
        endDate: "2024-05-30",
        members: [
            { id: "27", role: "PL", userId: "user27", firstName: "Jennifer", lastName: "Carter", email: "jennifer.carter@company.com" },
            { id: "28", role: "database_administrator", userId: "user28", firstName: "Steven", lastName: "Mitchell", email: "steven.mitchell@company.com" },
        ],
    },
    {
        id: "12",
        number: "P-2024-012",
        customer: "DevOps Solutions Ltd",
        status: "active",
        startDate: "2024-03-01",
        endDate: "2024-08-01",
        members: [
            { id: "29", role: "PL", userId: "user29", firstName: "Elizabeth", lastName: "Perez", email: "elizabeth.perez@company.com" },
            { id: "30", role: "devops_engineer", userId: "user30", firstName: "Andrew", lastName: "Roberts", email: "andrew.roberts@company.com" },
            { id: "31", role: "site_reliability_engineer", userId: "user31", firstName: "Stephanie", lastName: "Turner", email: "stephanie.turner@company.com" },
        ],
    },
    {
        id: "13",
        number: "P-2024-013",
        customer: "Testing Services AG",
        status: "active",
        startDate: "2024-02-05",
        endDate: "2024-05-05",
        members: [
            { id: "32", role: "PL", userId: "user32", firstName: "Matthew", lastName: "Phillips", email: "matthew.phillips@company.com" },
            { id: "33", role: "qa_engineer", userId: "user33", firstName: "Ashley", lastName: "Campbell", email: "ashley.campbell@company.com" },
            { id: "34", role: "test_automation_engineer", userId: "user34", firstName: "Brandon", lastName: "Parker", email: "brandon.parker@company.com" },
        ],
    },
    {
        id: "14",
        number: "P-2024-014",
        customer: "API Development GmbH",
        status: "active",
        startDate: "2024-01-20",
        endDate: "2024-06-20",
        members: [
            { id: "35", role: "PL", userId: "user35", firstName: "Melissa", lastName: "Evans", email: "melissa.evans@company.com" },
            { id: "36", role: "api_developer", userId: "user36", firstName: "Jonathan", lastName: "Edwards", email: "jonathan.edwards@company.com" },
        ],
    },
    {
        id: "15",
        number: "P-2024-015",
        customer: "Microservices Corp",
        status: "active",
        startDate: "2024-03-10",
        endDate: "2024-09-10",
        members: [
            { id: "37", role: "PL", userId: "user37", firstName: "Rebecca", lastName: "Collins", email: "rebecca.collins@company.com" },
            { id: "38", role: "software_architect", userId: "user38", firstName: "Nathan", lastName: "Stewart", email: "nathan.stewart@company.com" },
            { id: "39", role: "backend_developer", userId: "user39", firstName: "Christina", lastName: "Sanchez", email: "christina.sanchez@company.com" },
        ],
    },
    {
        id: "16",
        number: "P-2024-016",
        customer: "Blockchain Solutions AG",
        status: "active",
        startDate: "2024-02-15",
        endDate: "2024-08-15",
        members: [
            { id: "40", role: "PL", userId: "user40", firstName: "Timothy", lastName: "Morris", email: "timothy.morris@company.com" },
            { id: "41", role: "blockchain_developer", userId: "user41", firstName: "Heather", lastName: "Rogers", email: "heather.rogers@company.com" },
        ],
    },
    {
        id: "17",
        number: "P-2024-017",
        customer: "IoT Services GmbH",
        status: "active",
        startDate: "2024-01-25",
        endDate: "2024-07-25",
        members: [
            { id: "42", role: "PL", userId: "user42", firstName: "Jeffrey", lastName: "Reed", email: "jeffrey.reed@company.com" },
            { id: "43", role: "iot_engineer", userId: "user43", firstName: "Deborah", lastName: "Cook", email: "deborah.cook@company.com" },
            { id: "44", role: "embedded_systems_engineer", userId: "user44", firstName: "Brian", lastName: "Morgan", email: "brian.morgan@company.com" },
        ],
    },
    {
        id: "18",
        number: "P-2024-018",
        customer: "Machine Learning Corp",
        status: "active",
        startDate: "2024-03-05",
        endDate: "2024-10-05",
        members: [
            { id: "45", role: "PL", userId: "user45", firstName: "Sharon", lastName: "Bell", email: "sharon.bell@company.com" },
            { id: "46", role: "ml_engineer", userId: "user46", firstName: "Kenneth", lastName: "Murphy", email: "kenneth.murphy@company.com" },
            { id: "47", role: "data_scientist", userId: "user47", firstName: "Carol", lastName: "Bailey", email: "carol.bailey@company.com" },
        ],
    },
    {
        id: "19",
        number: "P-2024-019",
        customer: "Big Data Solutions AG",
        status: "active",
        startDate: "2024-02-20",
        endDate: "2024-08-20",
        members: [
            { id: "48", role: "PL", userId: "user48", firstName: "Ronald", lastName: "Richardson", email: "ronald.richardson@company.com" },
            { id: "49", role: "data_engineer", userId: "user49", firstName: "Donna", lastName: "Cox", email: "donna.cox@company.com" },
            { id: "50", role: "big_data_analyst", userId: "user50", firstName: "Joseph", lastName: "Ward", email: "joseph.ward@company.com" },
        ],
    },
    {
        id: "20",
        number: "P-2024-020",
        customer: "Cloud Native GmbH",
        status: "active",
        startDate: "2024-01-15",
        endDate: "2024-06-15",
        members: [
            { id: "51", role: "PL", userId: "user51", firstName: "Helen", lastName: "Torres", email: "helen.torres@company.com" },
            { id: "52", role: "cloud_architect", userId: "user52", firstName: "Dennis", lastName: "Peterson", email: "dennis.peterson@company.com" },
            { id: "53", role: "kubernetes_specialist", userId: "user53", firstName: "Diane", lastName: "Gray", email: "diane.gray@company.com" },
        ],
    },
    {
        id: "21",
        number: "P-2024-021",
        customer: "Serverless Solutions Ltd",
        status: "active",
        startDate: "2024-02-10",
        endDate: "2024-07-10",
        members: [
            { id: "54", role: "PL", userId: "user54", firstName: "Keith", lastName: "Ramirez", email: "keith.ramirez@company.com" },
            { id: "55", role: "serverless_developer", userId: "user55", firstName: "Joyce", lastName: "James", email: "joyce.james@company.com" },
        ],
    },
    {
        id: "22",
        number: "P-2024-022",
        customer: "Container Services AG",
        status: "active",
        startDate: "2024-01-30",
        endDate: "2024-05-30",
        members: [
            { id: "56", role: "PL", userId: "user56", firstName: "Samuel", lastName: "Watson", email: "samuel.watson@company.com" },
            { id: "57", role: "container_specialist", userId: "user57", firstName: "Brenda", lastName: "Brooks", email: "brenda.brooks@company.com" },
            { id: "58", role: "docker_expert", userId: "user58", firstName: "Eugene", lastName: "Kelly", email: "eugene.kelly@company.com" },
        ],
    },
    {
        id: "23",
        number: "P-2024-023",
        customer: "Monitoring Systems GmbH",
        status: "active",
        startDate: "2024-02-25",
        endDate: "2024-06-25",
        members: [
            { id: "59", role: "PL", userId: "user59", firstName: "Albert", lastName: "Sanders", email: "albert.sanders@company.com" },
            { id: "60", role: "monitoring_engineer", userId: "user60", firstName: "Dorothy", lastName: "Price", email: "dorothy.price@company.com" },
        ],
    },
    {
        id: "24",
        number: "P-2024-024",
        customer: "Backup Solutions Corp",
        status: "active",
        startDate: "2024-01-20",
        endDate: "2024-05-20",
        members: [
            { id: "61", role: "PL", userId: "user61", firstName: "Arthur", lastName: "Bennett", email: "arthur.bennett@company.com" },
            { id: "62", role: "backup_specialist", userId: "user62", firstName: "Virginia", lastName: "Wood", email: "virginia.wood@company.com" },
        ],
    },
    {
        id: "25",
        number: "P-2024-025",
        customer: "Disaster Recovery AG",
        status: "active",
        startDate: "2024-03-01",
        endDate: "2024-08-01",
        members: [
            { id: "63", role: "PL", userId: "user63", firstName: "Carlos", lastName: "Barnes", email: "carlos.barnes@company.com" },
            { id: "64", role: "dr_specialist", userId: "user64", firstName: "Nancy", lastName: "Ross", email: "nancy.ross@company.com" },
            { id: "65", role: "business_continuity_analyst", userId: "user65", firstName: "Gary", lastName: "Henderson", email: "gary.henderson@company.com" },
        ],
    },
    {
        id: "26",
        number: "P-2024-026",
        customer: "Compliance Services GmbH",
        status: "active",
        startDate: "2024-02-15",
        endDate: "2024-06-15",
        members: [
            { id: "66", role: "PL", userId: "user66", firstName: "Larry", lastName: "Coleman", email: "larry.coleman@company.com" },
            { id: "67", role: "compliance_officer", userId: "user67", firstName: "Betty", lastName: "Jenkins", email: "betty.jenkins@company.com" },
        ],
    },
    {
        id: "27",
        number: "P-2024-027",
        customer: "Performance Optimization Ltd",
        status: "active",
        startDate: "2024-01-25",
        endDate: "2024-06-25",
        members: [
            { id: "68", role: "PL", userId: "user68", firstName: "Roger", lastName: "Perry", email: "roger.perry@company.com" },
            { id: "69", role: "performance_engineer", userId: "user69", firstName: "Helen", lastName: "Powell", email: "helen.powell@company.com" },
        ],
    },
    {
        id: "28",
        number: "P-2024-028",
        customer: "Scalability Solutions AG",
        status: "active",
        startDate: "2024-02-20",
        endDate: "2024-07-20",
        members: [
            { id: "70", role: "PL", userId: "user70", firstName: "Howard", lastName: "Long", email: "howard.long@company.com" },
            { id: "71", role: "scalability_architect", userId: "user71", firstName: "Debra", lastName: "Patterson", email: "debra.patterson@company.com" },
            { id: "72", role: "load_testing_engineer", userId: "user72", firstName: "Gregory", lastName: "Hughes", email: "gregory.hughes@company.com" },
        ],
    },
];

export const mockGetProjects = async (page: number, pageSize: number): Promise<PaginatedResponse<FeProject>> => {
    const startIndex = (page - 1) * pageSize;
    const endIndex = startIndex + pageSize;
    const paginatedItems = mockProjects.slice(startIndex, endIndex);
    
    return {
        items: paginatedItems,
        total: mockProjects.length,
        page: page,
        pageSize: pageSize,
        totalPages: Math.ceil(mockProjects.length / pageSize),
    };
}