import {
  Card,
  CardContent,
  Badge,
  Button,
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@repo/pkg-frontend-common-kit/components";
import {
  ACMPFilterType,
  ComposedServiceViewReadModel,
} from "@scaleits-solutions-gmbh/omninode-lib-global-common-kit";
import { EllipsisVertical } from "lucide-react";

interface AcmpViewCardProps {
  acmpServiceView: ComposedServiceViewReadModel;
  onEdit?: (view: ComposedServiceViewReadModel) => void;
  onRemove?: (view: ComposedServiceViewReadModel) => void;
}

export default function AcmpViewCard({
  acmpServiceView,
  onEdit,
  onRemove,
}: AcmpViewCardProps) {
  const config = acmpServiceView.serviceView as {
    filterType: ACMPFilterType;
    filterValue1: string;
    filterValue2: string;
    canViewDashboard: boolean;
    canViewDevices: boolean;
    canViewJobs: boolean;
    canPushRollouts: boolean;
    canPushClientCommands: boolean;
    canViewAssets: boolean;
    canViewTickets: boolean;
  };

  const filterLabel =
    config.filterType === ACMPFilterType.Tenant ? "Tenant" : "None";

  const permissions: { label: string; enabled: boolean }[] = [
    { label: "Dashboard", enabled: config.canViewDashboard },
    { label: "Devices", enabled: config.canViewDevices },
    { label: "Jobs", enabled: config.canViewJobs },
    { label: "Rollouts", enabled: config.canPushRollouts },
    { label: "Client commands", enabled: config.canPushClientCommands },
    { label: "Assets", enabled: config.canViewAssets },
    { label: "Tickets", enabled: config.canViewTickets },
  ];

  const enabledPermissions = permissions.filter((p) => p.enabled);

  return (
    <Card className="h-full flex flex-col">
      <CardContent className="space-y-3 text-xs text-muted-foreground flex-1">
        <div className="flex items-start justify-between gap-2">
          <div className="flex flex-col gap-1">
            <h3 className="text-base leading-tight font-semibold text-foreground">
              {acmpServiceView.name}
            </h3>
            <div className="flex items-center gap-2 text-xs text-muted-foreground">
              <span>
                {acmpServiceView.isAutoGenerated ? "Auto-generated" : "Custom"}{" "}
                view
              </span>
            </div>
          </div>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                variant="ghost"
                size="icon"
                disabled={acmpServiceView.isAutoGenerated}
              >
                <EllipsisVertical className="h-4 w-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem
                onClick={() => {
                  onEdit?.(acmpServiceView);
                }}
              >
                Edit view
              </DropdownMenuItem>
              <DropdownMenuItem
                className="text-destructive hidden"
                onClick={() => {
                  onRemove?.(acmpServiceView);
                }}
              >
                Remove view
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
        <div className="space-y-1">
          <p className="font-medium text-foreground text-xs">Filter</p>
          <p>
            <span className="font-semibold">{filterLabel}</span>
            {config.filterType === ACMPFilterType.Tenant && (
              <>
                {" "}
                · Tenant ID:{" "}
                <span className="font-mono">{config.filterValue1}</span>
              </>
            )}
          </p>
        </div>
        <div className="space-y-1">
          <p className="font-medium text-foreground text-xs">Permissions</p>
          {enabledPermissions.length > 0 ? (
            <div className="flex flex-wrap gap-2">
              {enabledPermissions.map((perm) => (
                <Badge
                  key={perm.label}
                  variant="default"
                  className="text-[11px] px-2 py-0"
                >
                  {perm.label}
                </Badge>
              ))}
            </div>
          ) : (
            <p className="italic">No permissions granted</p>
          )}
    </div>
      </CardContent>
    </Card>
  );
}
