import { FeTicket } from "@/types/weclapp/ticket";
import { PaginatedResponse } from "@scaleits-solutions-gmbh/services";

export const mockTickets: FeTicket[] = [
    {
        id: "1",
        number: "T-2024-001",
        customer: "Edler & Stiegler Consulting GmbH",
        status: "open",
        date: "2024-01-15",
        finishedDate: "",
        priority: "high",
        authorFirstName: "John",
        authorLastName: "Doe",
        subject: "Login Issues",
        description: "Unable to access the system with my credentials. Getting authentication error.",
    },
    {
        id: "2",
        number: "T-2024-002",
        customer: "Tech Solutions AG",
        status: "in_progress",
        date: "2024-02-01",
        finishedDate: "",
        priority: "medium",
        authorFirstName: "Sarah",
        authorLastName: "Wilson",
        subject: "Feature Request - Export Functionality",
        description: "Need ability to export data in Excel format. Currently only CSV is available.",
    },
    {
        id: "3",
        number: "T-2024-003",
        customer: "Digital Innovations GmbH",
        status: "closed",
        date: "2024-01-20",
        finishedDate: "2024-01-25",
        priority: "low",
        authorFirstName: "Lisa",
        authorLastName: "Davis",
        subject: "UI Bug - Button Alignment",
        description: "The submit button on the form page is not properly aligned with other elements.",
    },
    {
        id: "4",
        number: "T-2024-004",
        customer: "Cloud Systems Ltd",
        status: "open",
        date: "2024-03-01",
        finishedDate: "",
        priority: "critical",
        authorFirstName: "David",
        authorLastName: "Garcia",
        subject: "System Down - Cannot Access Dashboard",
        description: "Complete system outage. Dashboard shows error 500 and cannot load any data.",
    },
    {
        id: "5",
        number: "T-2024-005",
        customer: "Data Analytics Corp",
        status: "in_progress",
        date: "2024-02-15",
        finishedDate: "",
        priority: "high",
        authorFirstName: "Rachel",
        authorLastName: "Martinez",
        subject: "Data Sync Issues",
        description: "Data is not syncing properly between modules. Some records are missing.",
    },
    {
        id: "6",
        number: "T-2024-006",
        customer: "Mobile Apps GmbH",
        status: "closed",
        date: "2024-01-10",
        finishedDate: "2024-01-18",
        priority: "medium",
        authorFirstName: "Amanda",
        authorLastName: "White",
        subject: "Mobile App Performance",
        description: "App is running slowly on iOS devices. Takes too long to load screens.",
    },
    {
        id: "7",
        number: "T-2024-007",
        customer: "Web Solutions AG",
        status: "open",
        date: "2024-02-20",
        finishedDate: "",
        priority: "low",
        authorFirstName: "Daniel",
        authorLastName: "Hall",
        subject: "Documentation Request",
        description: "Need updated API documentation for the new endpoints that were added.",
    },
    {
        id: "8",
        number: "T-2024-008",
        customer: "AI Technologies Ltd",
        status: "in_progress",
        date: "2024-03-15",
        finishedDate: "",
        priority: "high",
        authorFirstName: "Nicole",
        authorLastName: "King",
        subject: "AI Model Training Error",
        description: "Getting error during model training process. Logs show memory allocation failure.",
    },
    {
        id: "9",
        number: "T-2024-009",
        customer: "Security Systems GmbH",
        status: "closed",
        date: "2024-01-25",
        finishedDate: "2024-02-05",
        priority: "critical",
        authorFirstName: "Robert",
        authorLastName: "Scott",
        subject: "Security Vulnerability Found",
        description: "Discovered potential SQL injection vulnerability in user input fields.",
    },
    {
        id: "10",
        number: "T-2024-010",
        customer: "Network Solutions AG",
        status: "open",
        date: "2024-02-10",
        finishedDate: "",
        priority: "medium",
        authorFirstName: "Patricia",
        authorLastName: "Gonzalez",
        subject: "Network Connectivity Issues",
        description: "Experiencing intermittent connection drops when accessing the platform.",
    },
    {
        id: "11",
        number: "T-2024-011",
        customer: "Database Experts GmbH",
        status: "in_progress",
        date: "2024-01-30",
        finishedDate: "",
        priority: "high",
        authorFirstName: "Jennifer",
        authorLastName: "Carter",
        subject: "Database Performance",
        description: "Queries are taking too long to execute. Need optimization of database queries.",
    },
    {
        id: "12",
        number: "T-2024-012",
        customer: "DevOps Solutions Ltd",
        status: "closed",
        date: "2024-03-01",
        finishedDate: "2024-03-10",
        priority: "medium",
        authorFirstName: "Elizabeth",
        authorLastName: "Perez",
        subject: "Deployment Pipeline Issues",
        description: "CI/CD pipeline is failing during the build process. Need to fix build configuration.",
    },
    {
        id: "13",
        number: "T-2024-013",
        customer: "Testing Services AG",
        status: "open",
        date: "2024-02-05",
        finishedDate: "",
        priority: "low",
        authorFirstName: "Matthew",
        authorLastName: "Phillips",
        subject: "Test Environment Access",
        description: "Need access to the staging environment for testing new features.",
    },
    {
        id: "14",
        number: "T-2024-014",
        customer: "API Development GmbH",
        status: "in_progress",
        date: "2024-01-20",
        finishedDate: "",
        priority: "high",
        authorFirstName: "Melissa",
        authorLastName: "Evans",
        subject: "API Rate Limiting",
        description: "API calls are being rate limited too aggressively. Need to adjust limits.",
    },
    {
        id: "15",
        number: "T-2024-015",
        customer: "Microservices Corp",
        status: "closed",
        date: "2024-03-10",
        finishedDate: "2024-03-20",
        priority: "critical",
        authorFirstName: "Rebecca",
        authorLastName: "Collins",
        subject: "Service Discovery Failure",
        description: "Microservices are not able to discover each other. Service mesh is down.",
    },
    {
        id: "16",
        number: "T-2024-016",
        customer: "Blockchain Solutions AG",
        status: "open",
        date: "2024-02-15",
        finishedDate: "",
        priority: "medium",
        authorFirstName: "Timothy",
        authorLastName: "Morris",
        subject: "Smart Contract Deployment",
        description: "Having issues deploying smart contracts to the test network.",
    },
    {
        id: "17",
        number: "T-2024-017",
        customer: "IoT Services GmbH",
        status: "in_progress",
        date: "2024-01-25",
        finishedDate: "",
        priority: "high",
        authorFirstName: "Jeffrey",
        authorLastName: "Reed",
        subject: "IoT Device Integration",
        description: "IoT devices are not connecting properly to the platform. Connection timeout errors.",
    },
    {
        id: "18",
        number: "T-2024-018",
        customer: "Machine Learning Corp",
        status: "closed",
        date: "2024-03-05",
        finishedDate: "2024-03-15",
        priority: "medium",
        authorFirstName: "Sharon",
        authorLastName: "Bell",
        subject: "Model Accuracy Issues",
        description: "ML model accuracy has dropped significantly. Need to retrain with new data.",
    },
    {
        id: "19",
        number: "T-2024-019",
        customer: "Big Data Solutions AG",
        status: "open",
        date: "2024-02-20",
        finishedDate: "",
        priority: "critical",
        authorFirstName: "Ronald",
        authorLastName: "Richardson",
        subject: "Data Processing Pipeline Down",
        description: "Big data processing pipeline has stopped working. No data is being processed.",
    },
    {
        id: "20",
        number: "T-2024-020",
        customer: "Cloud Native GmbH",
        status: "in_progress",
        date: "2024-01-15",
        finishedDate: "",
        priority: "high",
        authorFirstName: "Helen",
        authorLastName: "Torres",
        subject: "Kubernetes Pod Issues",
        description: "Pods are being restarted frequently. Need to investigate resource constraints.",
    },
    {
        id: "21",
        number: "T-2024-021",
        customer: "Serverless Solutions Ltd",
        status: "closed",
        date: "2024-02-10",
        finishedDate: "2024-02-25",
        priority: "low",
        authorFirstName: "Keith",
        authorLastName: "Ramirez",
        subject: "Function Cold Start",
        description: "Serverless functions are taking too long to start up. Need optimization.",
    },
    {
        id: "22",
        number: "T-2024-022",
        customer: "Container Services AG",
        status: "open",
        date: "2024-01-30",
        finishedDate: "",
        priority: "medium",
        authorFirstName: "Samuel",
        authorLastName: "Watson",
        subject: "Docker Image Build Failures",
        description: "Docker images are failing to build in the CI/CD pipeline.",
    },
    {
        id: "23",
        number: "T-2024-023",
        customer: "Monitoring Systems GmbH",
        status: "in_progress",
        date: "2024-02-25",
        finishedDate: "",
        priority: "high",
        authorFirstName: "Albert",
        authorLastName: "Sanders",
        subject: "Alert System Not Working",
        description: "Monitoring alerts are not being sent. Email notifications are failing.",
    },
    {
        id: "24",
        number: "T-2024-024",
        customer: "Backup Solutions Corp",
        status: "closed",
        date: "2024-01-20",
        finishedDate: "2024-01-30",
        priority: "critical",
        authorFirstName: "Arthur",
        authorLastName: "Bennett",
        subject: "Backup Failure",
        description: "Automated backups are failing. No backups have been created for 3 days.",
    },
    {
        id: "25",
        number: "T-2024-025",
        customer: "Disaster Recovery AG",
        status: "open",
        date: "2024-03-01",
        finishedDate: "",
        priority: "high",
        authorFirstName: "Carlos",
        authorLastName: "Barnes",
        subject: "DR Test Failure",
        description: "Disaster recovery test failed. Systems did not recover properly.",
    },
    {
        id: "26",
        number: "T-2024-026",
        customer: "Compliance Services GmbH",
        status: "in_progress",
        date: "2024-02-15",
        finishedDate: "",
        priority: "medium",
        authorFirstName: "Larry",
        authorLastName: "Coleman",
        subject: "Compliance Report Generation",
        description: "Automated compliance reports are not generating correctly. Missing data.",
    },
    {
        id: "27",
        number: "T-2024-027",
        customer: "Performance Optimization Ltd",
        status: "closed",
        date: "2024-01-25",
        finishedDate: "2024-02-10",
        priority: "low",
        authorFirstName: "Roger",
        authorLastName: "Perry",
        subject: "Performance Degradation",
        description: "Application performance has degraded over the last week. Response times increased.",
    },
    {
        id: "28",
        number: "T-2024-028",
        customer: "Scalability Solutions AG",
        status: "open",
        date: "2024-02-20",
        finishedDate: "",
        priority: "critical",
        authorFirstName: "Howard",
        authorLastName: "Long",
        subject: "System Overload",
        description: "System is experiencing high load and cannot handle the current traffic volume.",
    },
];

export const mockGetTickets = async (search: string, page: number, pageSize: number): Promise<PaginatedResponse<FeTicket>> => {
    let filteredTickets = mockTickets;
    
    // Apply search filter if provided
    if (search) {
        const searchLower = search.toLowerCase();
        filteredTickets = mockTickets.filter(ticket => 
            ticket.number.toLowerCase().includes(searchLower) ||
            ticket.customer.toLowerCase().includes(searchLower) ||
            ticket.subject.toLowerCase().includes(searchLower) ||
            ticket.authorFirstName.toLowerCase().includes(searchLower) ||
            ticket.authorLastName.toLowerCase().includes(searchLower) ||
            ticket.description.toLowerCase().includes(searchLower)
        );
    }
    
    const startIndex = (page - 1) * pageSize;
    const endIndex = startIndex + pageSize;
    const paginatedItems = filteredTickets.slice(startIndex, endIndex);
    
    return {
        items: paginatedItems,
        total: filteredTickets.length,
        page: page,
        pageSize: pageSize,
        totalPages: Math.ceil(filteredTickets.length / pageSize),
    };
}