import {
  Card,
  CardContent,
  Badge,
  Button,
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@repo/pkg-frontend-common-kit/components";
import {
  ComposedServiceViewReadModel,
  WeclappFilterType,
} from "@scaleits-solutions-gmbh/omninode-lib-global-common-kit";
import { EllipsisVertical } from "lucide-react";

interface WeclappViewCardProps {
  weclappServiceView: ComposedServiceViewReadModel;
  onEdit?: (view: ComposedServiceViewReadModel) => void;
  onRemove?: (view: ComposedServiceViewReadModel) => void;
}

export default function WeclappViewCard({
  weclappServiceView,
  onEdit,
  onRemove,
}: WeclappViewCardProps) {
  const config = weclappServiceView.serviceView as {
    filterType: WeclappFilterType;
    filterValue: string;
    canViewDashboard: boolean;
    canViewQuotes: boolean;
    canViewSalesOrders: boolean;
    canViewInvoices: boolean;
    canViewProjects: boolean;
    canViewTickets: boolean;
    canCreateTickets: boolean;
    canRespondToTickets: boolean;
  };

  const filterLabel =
    config.filterType === WeclappFilterType.Organization
      ? "Organization"
      : "None";

  const permissions: { label: string; enabled: boolean }[] = [
    { label: "Dashboard", enabled: config.canViewDashboard },
    { label: "Quotes", enabled: config.canViewQuotes },
    { label: "Sales orders", enabled: config.canViewSalesOrders },
    { label: "Invoices", enabled: config.canViewInvoices },
    { label: "Projects", enabled: config.canViewProjects },
    { label: "Tickets", enabled: config.canViewTickets },
    { label: "Create tickets", enabled: config.canCreateTickets },
    { label: "Respond to tickets", enabled: config.canRespondToTickets },
  ];

  const enabledPermissions = permissions.filter((p) => p.enabled);

  return (
    <Card className="h-full flex flex-col">
      <CardContent className="space-y-3 text-xs text-muted-foreground flex-1">
        <div className="flex items-start justify-between gap-2">
          <div className="flex flex-col gap-1">
            <h3 className="text-base leading-tight font-semibold text-foreground">
              {weclappServiceView.name}
            </h3>
            <div className="flex items-center gap-2 text-xs text-muted-foreground">
              <span>
                {weclappServiceView.isAutoGenerated
                  ? "Auto-generated"
                  : "Custom"}{" "}
                view
              </span>
            </div>
          </div>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                variant="ghost"
                size="icon"
                disabled={weclappServiceView.isAutoGenerated}
              >
                <EllipsisVertical className="h-4 w-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem
                onClick={() => {
                  onEdit?.(weclappServiceView);
                }}
              >
                Edit view
              </DropdownMenuItem>
              <DropdownMenuItem
                className="text-destructive hidden"
                onClick={() => {
                  onRemove?.(weclappServiceView);
                }}
              >
                Remove view
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
        <div className="space-y-1">
          <p className="font-medium text-foreground text-xs">Filter</p>
          <p>
            <span className="font-semibold">{filterLabel}</span>
            {config.filterType === WeclappFilterType.Organization && (
              <>
                {" "}
                · Organization ID:{" "}
                <span className="font-mono">{config.filterValue}</span>
              </>
            )}
          </p>
        </div>
        <div className="space-y-1">
          <p className="font-medium text-foreground text-xs">Permissions</p>
          {enabledPermissions.length > 0 ? (
            <div className="flex flex-wrap gap-2">
              {enabledPermissions.map((perm) => (
                <Badge
                  key={perm.label}
                  variant="default"
                  className="text-[11px] px-2 py-0"
                >
                  {perm.label}
                </Badge>
              ))}
            </div>
          ) : (
            <p className="italic">No permissions granted</p>
          )}
        </div>
      </CardContent>
    </Card>
  );
}

